import type { APIRoute } from 'astro';

export const GET: APIRoute = async () => {
    const body = `---
title: Ask Joost's AI
description: Ask a question about SEO, WordPress, open source, or the web and get an AI-powered answer grounded in Joost de Valk's posts and videos.
canonical: https://joost.blog/ask-joost/
---

# Ask Joost's AI

Ask a question about anything I've written about. Answers are generated by AI based on my blog posts. They may not always be perfectly accurate — but they're grounded in what I've actually published.

The page at [joost.blog/ask-joost/](https://joost.blog/ask-joost/) is interactive and requires a browser. Suggested starter questions:

- What's your take on WordPress' market share?
- What is Emilia Capital?
- How do you think AI will affect SEO?
- Why did you leave Yoast?
- Astro vs. WordPress for a new blog?

For agents and crawlers: my full archive is available at [/blog/](https://joost.blog/blog/) and a machine-readable index lives at [/llms.txt](https://joost.blog/llms.txt).
`;

    return new Response(body, {
        headers: {
            'Content-Type': 'text/markdown; charset=utf-8',
            Link: '<https://joost.blog/ask-joost/>; rel="canonical"'
        }
    });
};
