// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  url?: string;
  github_url?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  featured?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Video {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  video_url?: string;
  youtube_id?: string;
  duration?: string;
  featured?: boolean;
  transcript?: string;
  on_stage?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
    projects: Project;
    videos: Video;
  }
}